// ---
// layout: post
// title: Install the UnifiedPush Server
// section: guides
// ---

[[server-installation]]
== Install and Configure the UnifiedPush Server

Getting the UnifiedPush Server up and running with an on-premise application server is a four-step setup process:

. <<getfiles,Get the UnifiedPush Server application files>>
. <<gendbds,Generate the UnifiedPush database and datasource>>
. <<schema,Create the database schema>>
. <<deploy,Deploy the UnifiedPush Server>>

Each of these steps is detailed here, with instructions and useful scripts provided for the supported databases (MySQL, PostgreSQL) and application servers. __Make sure to run them in the **full-profile** mode as discussed below!__

Find below the required application server version:

* UnifiedPush Server version 1.1.x - link:https://developers.redhat.com/products/eap/download/[EAP 6.4.0 GA]or link:http://wildfly.org/downloads/[WildFly 8.x]
* UnifiedPush Server 1.2.x - link:https://developers.redhat.com/products/eap/download/[EAP 7.x] or link:http://wildfly.org/downloads/[WildFly 10.x]

NOTE: You can also link:#openshift[run the UnifiedPush Server in the cloud with OpenShift] but this requires a different setup process.

Extract the downloaded archive in a directory of your choice and save that path in an environment variable

*UNIX*
[source,shell]
----
export APPSRV_HOME=/path/to/SERVER_HOME
----

*WINDOWS*
[source,batch]
----
set APPSRV_HOME=X:\path\to\SERVER_HOME
----

[[getfiles]]
=== Get the UnifiedPush Server Application Files
The UnifiedPush Server application is provided in two files: +unifiedpush-server.war+ and +unifiedpush-auth-server.war+. These files contain the core functionality and authentication components of the UnifiedPush Server. Both files are necessary to achieve a working UnifiedPush Server application.

Download the latest copies of these files using the following link:

* link:https://github.com/aerogear/aerogear-unifiedpush-server/releases/tag/1.1.3.Final[Download UnifiedPush Server Release Bundle]

Different files are provided for each application servers:

** For WildFly, +unifiedpush-server-wildfly.war+
** For EAP, +unifiedpush-server-as7.war+

Extract the downloaded archive in a working directory of your choice and save that path in an environment variable.

*UNIX*
[source,shell]
----
export WORK_DIR=/path/to/WORK_DIR
----

*WINDOWS*
[source,c]
----
set WORK_DIR=X:\path\to\WORK_DIR
----

From now on we will refer only to unix syntax. It will be, however, pretty simple to convert the commands to the Windows syntax.

[[confjms]]
=== Configure JMS destinations for the UnifiedPush
The UnifiedPush Server 1.2.x requires JMS queues and topics that it uses for token loading, notification dispatching and metrics collection.

Following CLI script creates all required JMS destinations and also configures address settings that influence JMS destinations behavior:

[source,shell]
----
$ $APPSRV_HOME/bin/jboss-cli.sh --file=$WORK_DIR/configuration/jms-setup-wildfly.cli
----

[[gendbds]]
=== Generate the UnifiedPush Database and Datasource
The UnifiedPush Server requires an accompanying database in which to store push application, variant and installation details. You can use the database of your choice but the corresponding datasource added to the application server must have JNDI name +java:jboss/datasources/UnifiedPushDS+.

Information is provided here for generating UnifiedPush datasources for several database types. Note that if the intended application server has not previously been used with the chosen database type, additional configuration must also be completed in order to enable the application server to connect to the database. As detailed here, sources and scripts are available to assist with all these processes.

==== MySQL Database
You can use a link:http://www.mysql.com/[MySQL] database with the UnifiedPush Server. As demonstrated here, the application server must first be configured for MySQL and the UnifiedPush MySQL database must exist before the application server can be configured with the associated UnifiedPush datasource.

To complete these prerequisite processes and configure the application server for the UnifiedPush MySQL database, complete the following steps:

. Copy the MySQL module, located in the +databases/src/main/resources/modules/com+ directory of the release bundle, to the application server modules directory
+
[source,shell]
----
$ cp -r $WORK_DIR/databases/src/main/resources/modules/com $APPSRV_HOME/modules/
----
. Add the MySQL JDBC driver to the application server +mysql+ module
+
[source,shell]
----
$ mvn dependency:copy -Dartifact=mysql:mysql-connector-java:5.1.44 -DoutputDirectory=$APPSRV_HOME/modules/com/mysql/jdbc/main/
----
. Create the UnifiedPush MySQL database
+
For 1.0.x :
+
[source,SQL]
----
$ mysql -u <user-name>
mysql> create database unifiedpush default character set = "UTF8" default collate = "utf8_general_ci";
mysql> create user 'unifiedpush'@'localhost' identified by 'unifiedpush';
mysql> GRANT SELECT,INSERT,UPDATE,ALTER,DELETE,CREATE,DROP ON unifiedpush.* TO 'unifiedpush'@'localhost';
----
+
For 1.1.x :
+
[source,SQL]
----
$ mysql -u <user-name>
mysql> create database unifiedpush default character set = "UTF8" default collate = "utf8_general_ci";
mysql> create database keycloak default character set = "UTF8" default collate = "utf8_general_ci";
mysql> create user 'unifiedpush'@'localhost' identified by 'unifiedpush';
mysql> GRANT SELECT,INSERT,UPDATE,ALTER,DELETE,CREATE,DROP,INDEX ON unifiedpush.* TO 'unifiedpush'@'localhost';
mysql> GRANT SELECT,INSERT,UPDATE,ALTER,DELETE,CREATE,DROP ON keycloak.* TO 'unifiedpush'@'localhost';
----

. Start the application server, using the full-profile mode
+
[source,shell]
----
$ $APPSRV_HOME/bin/standalone.sh --server-config=standalone-full.xml
----
. Configure the application server to use the MySQL driver and create and add the UnifiedPush datasource for the MySQL database using the application server CLI and downloaded configuration script, located in the +databases+ directory of the release bundle
+
For WildFly:
+
[source,shell]
----
$ $APPSRV_HOME/bin/jboss-cli.sh --file=$WORK_DIR/databases/mysql-database-config-wildfly.cli
----
+
For EAP:
+
[source,shell]
----
$ $APPSRV_HOME/bin/jboss-cli.sh --file=$WORK_DIR/databases/mysql-database-config.cli
----

==== PostgreSQL Database
You can use a link:http://www.postgresql.org/[PostgreSQL] database with the UnifiedPush Server. As demonstrated here, the application server must first be configured for PostgreSQL and the UnifiedPush PostgreSQL database must exist before the application server can be configured with the associated UnifiedPush datasource.

To complete these prerequisite processes and configure the application server for the UnifiedPush PostgreSQL database, complete the following steps:

. Copy the PostgreSQL module, located in the +databases/src/main/resources/modules/org+ directory of the release bundle, to the application server modules directory
+
[source,shell]
----
$ cp -r $WORK_DIR/databases/src/main/resources/modules/org $APPSRV_HOME/modules/
----
. Add the PostgreSQL JDBC driver to the application server +postgresql+ module
+
[source,c]
----
$ mvn dependency:copy -Dartifact=org.postgresql:postgresql:9.2-1004-jdbc41 -DoutputDirectory=$APPSRV_HOME/modules/org/postgresql/main/
----
. Create the UnifiedPush PostgreSQL database
+
For 1.0.x :
+
[source,SQL]
----
$ psql -U <user-name>
psql> create database unifiedpush;
psql> create user unifiedpush with password 'unifiedpush';
psql> GRANT ALL PRIVILEGES ON DATABASE unifiedpush to unifiedpush;
----
For 1.1.x :
+
[source,SQL]
----
$ psql -U <user-name>
psql> create database unifiedpush;
psql> create database keycloak;
psql> create user unifiedpush with password 'unifiedpush';
psql> GRANT ALL PRIVILEGES ON DATABASE unifiedpush to unifiedpush;
psql> GRANT ALL PRIVILEGES ON DATABASE keycloak to unifiedpush;
----
. If necessary, enable UnifiedPush Server access to the PostgreSQL database by adding the following lines to your +$POSTGRES_HOME/data/pg_hba.conf+ file
+
[source,c]
----
host    all             unifiedpush     127.0.0.1/32            md5
----
. Start the application server, using the full-profile mode
+
[source,c]
----
$ $APPSRV_HOME/bin/standalone.sh --server-config=standalone-full.xml
----
. Configure the application server to use the PostgreSQL driver and create and add the UnifiedPush datasource for the PostgreSQL database using the application server CLI and downloaded configuration script, located in the +databases+ directory of the release bundle
+
For WildFly:
+
[source,shell]
----
$ $APPSRV_HOME/bin/jboss-cli.sh --file=$WORK_DIR/databases/postgresql-database-config-wildfly.cli
----
+
For EAP:
+
[source,shell]
----
$ $APPSRV_HOME/bin/jboss-cli.sh --file=$WORK_DIR/databases/postgresql-database-config.cli
----

[[schema]]
=== Create the database schema

After the application server is configured for the UnifiedPush datasource, the schema must be created. Inside of the release bundle there is a +migrator+ folder which contains a command line interface to create the required database schema. The tool is also used to migrate from an existing schema to a newer version of the schema, used for the UnifiedPush Server.

Copy the _liquibase example_ file to  +liquibase.properties+ and edit it to match your database name and credentials.


[source,shell]
----
cp liquibase-database-flavor-example.properties liquibase.properties
----

After the +liquibase.properties+ contains the proper credentials, you need to execute the migration tool:

[source,shell]
----
./bin/ups-migrator update
----

In case of a successful run, the script prints

[source,c]
----
Liquibase Update Successful
----

[[deploy]]
=== Deploy the UnifiedPush Server
With the database schema in place, the two UnifiedPush Server application +.war+ files must both be deployed to the application server to achieve a complete and operational UnifiedPush Server.

To deploy the UnifiedPush Server, copy the two +.war+ files to +$APPSRV_HOME/standalone/deployments/+. This can be done either before or after starting the application server.

After deployment with the application server running, the UnifiedPush Server Console can be accessed at link:http://localhost:8080/ag-push/[]. For information about using the Console, see link:#admin-ui[Using the Admin UI].

=== Database Migration

For migrating the database schema to a new version the migration tool from the above link:#schema[Create the database schema] section is used. For details around the database migration, consult the link:#migration-guide[Migration guide].
