source 'https://rubygems.org'

gem 'RedCloth', '4.2.9'
gem 'jekyll', '2.5.2'
gem 'net-sftp', '2.1.2'
gem 'asciidoctor', '1.5.2'
gem 'kramdown', '1.6.0'
gem 'rouge', '1.8.0'
gem 'less', '2.6.0'
gem 'therubyracer', '0.12.1'
gem 'curb'
gem 'diskcached'
gem 'html-proofer'
