[[troubleshooting]]
## Android Troubleshooting

This troubleshooting guide takes as a pre-requesite that you have carefully followed the instructions in the link:../index.html[Android tutotial].

We've documented some of the common configuration failures in this guide.  If you are having issues which we don't cover or otherwise need help, feel free to post to our link:link:https://lists.jboss.org/mailman/listinfo/aerogear-users/[user list].

### Issue: Registration fails with the error "SERVICE_NOT_AVAILABLE"

*Problem description*

When you call `PushRegistrar.register` onFailure is called with the exception message "SERVICE_NOT_AVAILABLE".

*Answer*

There are several causes for this issue.  The easiest solution is that the FCM registration service had an error and you should retry at a later date.  However, there are also several code/environment issues to check.

. You do not have Google Play Services installed on your device. +
If you are running an emulator, make sure you are using a Google APIs Target higher than Android 4.2. If you are using a device, make sure you are using a Google experience device and not an Amazon Fire or AOSP device.

. Make sure the *permission* and *uses-permission* tags in AndroidManifest.xml have the correct package.
+
[source,xml]
----
<permission android:name="YOUR_PACKAGE_NAME.permission.C2D_MESSAGE"
       android:protectionLevel="signature" />
<uses-permission android:name="YOUR_PACKAGE_NAME.permission.C2D_MESSAGE" />
----

. Make sure you have the correct permissions available.
+
[source,xml]
----
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.GET_ACCOUNTS" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

<permission android:name="YOUR_PACKAGE_NAME.permission.C2D_MESSAGE"
       android:protectionLevel="signature" />
<uses-permission android:name="YOUR_PACKAGE_NAME.permission.C2D_MESSAGE" />
----

. Make sure your device's clock is set correctly.  Some people on link:http://stackoverflow.com/questions/17188982/how-to-fix-google-cloud-messaging-registration-error-service-not-available[Stack Overflow] have reported this issue.

### Issue: Registration fails with INVALID_SENDER

*Problem description*

When you call `PushRegistrar.register` onFailure is called with the exception message "INVALID_SENDER".

*Answer*

Make sure the SenderID matches the project number from the Google API Console.  This will be an link:../img/gcc_3.png[all numeric string].

### I have another Issue

If you are having issues which we don't cover or otherwise need help, feel free to post to our link:https://lists.jboss.org/mailman/listinfo/aerogear-users[mailing list].  Also, messages in logcat may give useful results from Google or StackOverflow.
