== Managing Digger Build Logs and Artifacts
App builds started by Digger produce build logs and build artifacts.
Over time, these will build up. There are a number of options to manage the buildup. If you are using Digger with RHMAP, these options can be specified
by setting environment variables in the `millicore` deployment configuration in
RHMAP. Configuration options found in Jenkins along with associated RHMAP properties are detailed below.

NOTE: Entire Jenkins configuration regarding Digger artifacts can be performed using the
GUI in  `<Job Name> -> Configure -> Discard Old Builds` with the
`Log Rotation` strategy enabled.

|===
| Option | Configure in Jenkins | RHMAP property

| Days to keep builds
| Set the `Days to keep builds` to an integer.
| BUILDFARM_BUILDS_DAYS

| Max number of builds to keep
| Set the `Max # of builds to keep` to the number 
of total build records to keep indefinitely.
| BUILDFARM_BUILDS_TOTAL

| Days to keep artifacts
| Set the `Days to keep artifacts` to the number of days to retain the build artifacts.
| BUILDFARM_ARTIFACTS_DAYS

| Total number of builds to keep with artifacts
| Set the `Max # of builds to keep with artifacts` to the amount of
builds with artifacts to keep indefinitely.
| BUILDFARM_ARTIFACTS_TOTAL
|===