== Using HTTP/HTTPS Proxy with Aerogear Digger

WARNING: HTTP Proxies that require authentication are not supported.
Please check the link:known_issues[Known Issues] for more details.

If you want to install AeroGear Digger behind proxy, the installer will (once provided with the required variables) automatically configure the following components to use the proxy (if an outbound Internet access is required):

* The Jenkins server
* The Android SDK pod used to download Android SDKs
* Container/node that will run the build jobs, by adding the appropriate environment variables like `HTTP_PROXY` and `HTTPS_PROXY` in the inventory file. 
Sample provided in https://github.com/aerogear/digger-installer/blob/master/inventory-sample[AeroGear Digger GitHub repo].
* macOS servers used to run iOS builds

=== Ansible Variables Regarding HTTP/HTTPS Proxy

You can run AeroGear Digger behind a HTTP proxy server by setting the following Ansible Variables:

|===
| Variable name | Description
| proxy_url
| This URL is pasted into `http_proxy` and `https_proxy` environment variables.
| proxy_host
| The host name of the proxy server. Follow URL format `<host>:<port>` e.g. `127.0.0.1:8080`
| proxy_port
| The port number of the proxy
| proxy_user
| Required if proxy authentication is enabled
| proxy_pass
| Required if proxy authentication is enabled
| proxy_protocol
| Optional. The protocol to use with the proxy. Default value is `http`.
|===

You can define these variables either in an inventory file, or via CLI.
Please refer to the http://docs.ansible.com/ansible/playbooks_variables.html[Ansible Playbook Variables Docs] for more details.

=== Using external tools with HTTP/HTTPS Proxy

If you want to use any external tools with HTTP/HTTPS proxy, you will have to manually update the configuration for those tools  in the Jenkinsfile, using the values from the environment variables such as `HTTP_PROXY` and `HTTPS_PROXY`.