---
layout: basic
title: AeroGear UnifiedPush Authentication
---

Authentication and Developer API
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The RESTful APIs for authentication and Developer management:

Login (+HTTP POST+)
^^^^^^^^^^^^^^^^^^^

JSON Payload:
[source,json]
----
{
  "loginName" : "misterX",
  "password" : "forgotten"
}
----

URL:
[source,c]
----
https://server:port/context/rest/auth/login
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 200 OK+
Indicates the authentication has been successful.

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 400 Bad Request+
The format of the client request was incorrect (e.g. user session still active).

* +HTTP/1.1 401 Unauthorized+
Incorrect credentials applied.

* +HTTP/1.1 403 Forbidden+
Expired credentials applied.

Logout (+HTTP POST+)
^^^^^^^^^^^^^^^^^^^^

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

[source,c]
----
https://server:port/context/rest/auth/logout
----

* +HTTP/1.1 200 OK+
Indicates the logout has been successful.

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

Update Password (+HTTP PUT+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

JSON Payload:
[source,json]
----
{
  "loginName" : "misterX",
  "password" : "currentPassword",
  "newPassword" : "theNewPassword"
}
----

URL:
[source,c]
----
https://server:port/context/rest/auth/update
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 200 OK+
Indicates the password update has been successful.

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
Incorrect credentials applied.

Enroll new +Developer+ (+HTTP POST+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

JSON Payload:
[source,json]
----
{
  "loginName" : "misterX",
  "password" : "forgotten",
  "email" : "misterX@somedomain.foo",
  "firstName" : "Mister",
  "lastName" : "X"
}
----

URL:
[source,c]
----
https://server:port/context/rest/admin/enroll
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 200 OK+
The Body will contain (JSON) details about the specific _Developer_:
[source,json]
----
{
  "loginName" : "misterX",
  "password" : "forgotten",
  "email" : "misterX@somedomain.foo",
  "firstName" : "Mister",
  "lastName" : "X"
}
----

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 400 Bad Request+
The format of the client request was incorrect (e.g. missing required values).

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.
