---
layout: basic
title: AeroGear UnifiedPush Device Registration
---

APIs for Device/Installation Registration
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The RESTful APIs for Device/Installation Registration are explained below:


Device Registration (+HTTP POST+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Endpoint _protected_ with +HTTP BASIC+. Credentials: +variantID:secret+

JSON Payload:
[source,json]
----
{
  "deviceToken" : "someTokenString",
  "deviceType" : "iPad",
  "operatingSystem" : "iOS",
  "osVersion" : "6.1.2",
  "alias" : "someUsername or email adress...",
  "category" : "football",
  "simplePushEndpoint":"http://server.com/endpointPath"
}
----

URL:
[source,c]
----
http://server:port/context/rest/registry/device
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* _HTTP/1.1 200 OK_
On successful storage of the device related metadata:

[source,json]
----
{
  "id":"402880e43fa95bb3013fa960f9ee0002",
  "deviceToken":"someTokenString",
  "deviceType":"iPad",
  "operatingSystem":"iOS",
  "osVersion":"6.1.2",
  "alias":"dude@dude.org",
  "category":"football",
  "simplePushEndpoint":"http://server.com/endpointPath"
}
----

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 400 Bad Request+
The format of the client request was incorrect (e.g. missing required values).

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource (_PushApplication_ or _MobileVariants_) does not exist.


Unregister of a device (+HTTP DELETE+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
http://server:port/context/rest/registry/device/{deviceToken}
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 204 No Content+
Empty body.

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource (_device metadata_) does not exist.
