---
layout: basic
title: AeroGear UnifiedPush working with PushApplication
---

APIs for working with PushApplication
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Registration of a *PushApplication* (+HTTP POST+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
http://server:port/context/rest/applications
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 201 Created+
The Body will contain (JSON) details about the created _PushApplication_

Failure status code and desciption
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 400 Bad Request+
The format of the client request was incorrect (e.g. missing required values).

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

Read all *PushApplications* (+HTTP GET+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
http://server:port/context/rest/applications
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 200 OK+
The Body will contain a JSON list of the _PushApplications_.

Failure status code and desciption
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.


Read a specific *PushApplication* (+HTTP GET+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
http://server:port/context/rest/applications/{PUSH_APP_ID}
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 200 OK+
The Body will contain (JSON) details about the _PushApplication_

Failure status code and desciption
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource does not exist.


Update a specific *PushApplication* (+HTTP PUT+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
http://server:port/context/rest/applications/{PUSH_APP_ID}
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 204 No Content+
Empty body.

Failure status code and desciption
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 400 Bad Request+
The format of the client request was incorrect  (e.g. missing required values).

* +HTTP/1.1 401 Unauthorized+ 
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource does not exist.


Delete a specific *PushApplication* (+HTTP DELETE+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
http://server:port/context/rest/applications/{PUSH_APP_ID}
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 204 No Content+
Empty body.

Failure status code and desciption
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource does not exist.
