---
layout: basic
title: AeroGear UnifiedPush working with PushApplication
---

APIs for working with PushApplication
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The RESTful APIs for working with +PushApplications+ are explained below:

Creation of a *PushApplication* (+HTTP POST+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

JSON Payload:
[source,json]
----
{
  "name" : "MyApp",
  "description" : "awesome app"
}
----

URL:
[source,c]
----
https://SERVER:PORT/CONTEXT/rest/applications
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 201 Created+
The Body will contain (JSON) details about the created _PushApplication_:
[source,json]
----
{
  "id":"402880e43fa95bb3013faf1196c30004",
  "name":"MyApp",
  "description":"awesome app",
  "pushApplicationID":"c4c7bd2a-9eb0-4613-90fe-43c214424d69",
  "masterSecret":"cdba924f-ab55-4f74-af40-3d6d8f823115",
  "developer":"admin",
  "androidVariants":[],
  "simplePushVariants":[],
  "iosvariants":[],
  "chromePackagedAppVariants":[]
}
----

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 400 Bad Request+
The format of the client request was incorrect (e.g. missing required values).

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

Read all *PushApplications* (+HTTP GET+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
https://SERVER:PORT/CONTEXT/rest/applications
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 200 OK+
The Body will contain a JSON array of the _PushApplications_, for the current user:

----
[
  {
    "id":"402880e43fa95bb3013faf1196c30004",
    "name":"MyApp",
    "description":"awesome app",
    ....
  },
  {...}
]
----

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.


Read a specific *PushApplication* (+HTTP GET+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
https://SERVER:PORT/CONTEXT/rest/applications/{pushApplicationID}
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 200 OK+
The Body will contain (JSON) details about the _PushApplication_:

[source,json]
----
{
  "id":"402880e43fa95bb3013faf1196c30004",
  "name":"MyApp",
  "description":"awesome app",
  "pushApplicationID":"c4c7bd2a-9eb0-4613-90fe-43c214424d69",
  "masterSecret":"cdba924f-ab55-4f74-af40-3d6d8f823115",
  "developer":"admin",
  "androidVariants":[],
  "simplePushVariants":[],
  "iosvariants":[],
  "chromePackagedAppVariants":[]
}
----

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource does not exist.


Update a specific *PushApplication* (+HTTP PUT+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
JSON Payload:
[source,json]
----
{
  "name" : "MyApp",
  "description" : "really awesome app"
}
----

URL:
[source,c]
----
https://SERVER:PORT/CONTEXT/rest/applications/{pushApplicationID}
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 204 No Content+
Empty body.

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 400 Bad Request+
The format of the client request was incorrect  (e.g. missing required values).

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource does not exist.


Delete a specific *PushApplication* (+HTTP DELETE+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
https://SERVER:PORT/CONTEXT/rest/applications/{pushApplicationID}
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 204 No Content+
Empty body.

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource does not exist.
