=== How Installer installs Android SDK
//pwright: I think heading should be task oriented, ie run playbook
To build Android applications, Jenkins will dynamically create containers (pods) on OpenShift using the https://wiki.jenkins.io/display/JENKINS/Kubernetes+Plugin[Kubernetes Jenkins plugin]. This approach has a few advantages:

* It doesn't require a build server to be running constantly
* Each build is performed completely in isolation

The Android SDK is required to build Android apps. The installer will download the Android SDK and make it available to the building pods by performing the following tasks:

* Creating a new pod which will be used to download the Android SDK. The pod will use an image that contains the required tools, and claim a Persistent Volume(PV).
* Invoke a script to download the Android SDK. During the process, the user will be prompted to accept the Android SDK License Agreement. The Android SDK will be persisted in the PV.
* Update the Kubernetes plugin configuration to add a new pod template. It will mount the PV in “Read-Only” mode to the pods and setup the required environment variables to define an Android home directory.

==== Configuring of Android SDK components 

The Android SDK contains many different components. 
Only a subset of them are installed by default.
The list of components that will be installed are specified https://github.com/aerogear/digger-installer/blob/master/android-sdk/templates/sample_cfg.j2[in this file] contained in digger-installer repo .

You can modify this file to select the Android SDK components to be installed.