== Prerequisites

The main components (jenkins, android-sdk, nagios) of the digger project are deployed to an OpenShift Container Platform. With these components installed, digger has the capability to build Android Applications. The user has the option to configure (via the digger installer) a macOS server to allow for iOS Application builds. This is an optional step and the macOS Server pre-requisites section below can be ignore if a macOS is not part of the installation.

Before running the Digger installer, please make sure the following prerequisites are met:

=== General pre-requisites

==== Ansible 2.2.3 or higher

Digger Installer requires a version of Ansible 2.2.3 or higher on the machine that the Ansible playbook will be executed from. You can check the installed Ansible version by running `ansible --version`.
Please check http://docs.ansible.com/ansible/intro_installation.html[Ansible installation instructions] for information on how to install.

==== Outbound internet access

Digger requires outbound internet access to perform npm installations. Make sure that all relevant nodes/servers have outbound internet access.

==== Proxy Configuration (optional)

If your environments are on a network behind a proxy, this can be configured through the installer. Digger supports HTTP proxy without authentication. Digger does not currently HTTP support proxy with authentication. See Known Issues for further details.

=== Java 2.2 and higher

Java is required for some configuration of Jenkins during the installation. If Jave is not present the installer will install it.

=== OpenShift pre-requisites

==== OpenShift 3.3 or higher

* An OpenShift Container Platform, and its command line tool (https://github.com/openshift/origin/releases/tag/v1.3.1[oc^]) installed locally.
* The OpenShift cluster should have the following PVs (Persistent Volumes) available
** 40GB for Jenkins
** 10GB for Android-sdk
** 1GB for Nagios

==== Access to dockerhub

The installer retrieves the relevant docker formatted images from https://hub.docker.com/. Please ensure that all nodes in the OpenShift Installation have access to this site.
