== Digger Installation Introduction
//Please DO NOT use 'Overview' as a section heading anywhere http://stylepedia.net/#sect-Red_Hat_Technical_Publications-Writing_Style_Guide-Overall_Book_Design-Unused_Heading_Titles

The AeroGear Digger project allows you to setup a service builds mobile applications using OpenShift containers.
//DON'T USE PASSIVE VOICE

It is made of following components:

* A Jenkins server that is used to run the build tasks
* A Docker-formated image with all the required tools to build Android applications
* macOS servers with pre-installed tools to build iOS applications
* An http://docs.ansible.com/ansible/index.html[Ansible] based automation tool used to install and configure all the components
* A suite of sample Jenkinsfiles to demonstrate how to build mobile applications using Jenkins pipeline

The main objective of this project is to be used with the RedHat Application Platform (RHMAP).
However, it will be possible to use it on its own as a CI/CD server for mobile applications.
