=== How to install Android SDK with Ansible
//pwright: I think heading should be task oriented, ie run playbook
//pmacko: +1, changed to active form
WARNING: During the process, you will be ask to manually accept the Android SDK License Agreement.
 
The Android SDK is required to build Android apps. The installer downloads the Android SDK and makes it available to the building pods by performing the following steps:

* Creating a pod which will be used to download the Android SDK. The pod will use an image that contains the required tools, and claim a Persistent Volume (PV).
* Invoke a script to download the Android SDK. The Android SDK will be retained in the PV.
* Update the Kubernetes plugin configuration to add a new pod template. It will mount and connect the PV in “Read-Only” mode to the pods, and setup the required environment variables to define an Android home directory.

Jenkins dynamically creates containers (pods) on OpenShift using the https://wiki.jenkins.io/display/JENKINS/Kubernetes+Plugin[Kubernetes Jenkins plugin] for each Android build.

//* It doesn't require a build server to be running constantly
//* Each build is performed completely in isolation -> redundant I think, good for "marketing", otherwise I think not, ppl are familiar with containers


==== Configure Android SDK components 

The Android SDK contains many different components. Only a subset of them are installed by default.
The list of installed components are specified https://github.com/aerogear/digger-installer/blob/master/android-sdk/templates/sample_cfg.j2[in this file] contained in `digger-installer` repo .

You can modify this file to select which Android SDK components you want to install.