=== Mac Server

This is only required for building iOS applications.

==== Mac Machine Setup

- Set `ansible_sudo_pass` variable for the Ansible job to enable the Installer to work with root permissions. It is required by several installation steps.

.macOS Scripts: https://github.com/aerogear/digger-jenkins/blob/master/admin/create-osx-user.sh[create-osx-user.sh] https://github.com/aerogear/digger-jenkins/blob/master/admin/enable-osx-remote-login.sh[enable-osx-remote-login.sh]
- Set up a user with sudo permissions and SSH access.
These scripts will create a user named `jenkins` with SSH access.
It is highly recommended that you read these scripts and change the `PASSWORD`
variable in `create-osx-user.sh` to a strong passphrase:
    

--
  
. Download the scripts into the target macOS machine:
+
[source,bash]
----
curl -O https://raw.githubusercontent.com/aerogear/digger-jenkins/master/admin/create-osx-user.sh
curl -O https://raw.githubusercontent.com/aerogear/digger-jenkins/master/admin/enable-osx-remote-login.sh
----
+
. Edit the `PASSWORD` for the Jenkins user in `create-osx-user.sh`.
. Execute `create-osx-user.sh` with the updated password:
+
----
sudo bash create-osx-user.sh
----
+
. Execute `enable-osx-remote-login.sh` to allow SSH access:
+
----
sudo bash enable-osx-remote-login.sh
----
--
==== Network access
The macOS preparation can be optionally done using a proxy.

The machine requires a network access to the following hosts:

.Required resources
|===
| Hostname | Reason

| https://github.com
| To download and install Homebrew packages and Cocoapods.

| https://raw.githubusercontent.com
| To download and install NVM.

| https://rvm.io
| To download and install RVM.

| http://developer.apple.com
| To download developer certificates and Xcode.

| https://npmjs.org
| To install NPM packages.
|===
Other external hosts may be required depending on what other packages you specify to install. ???