[[macos-prereqs]]
=== macOS Prerequisites (optional)

NOTE: Completing the steps presented in this section are only required to provision a macOS server to enable iOS app building with Aerogear Digger. Please skip to link:#run-digger-installer[Run Digger Installer] if you don't need this functionality.

==== Recommended macOS Server Specifications:

* A fresh macOS 10.12 Sierra install (MacinCloud service can be used, too)
* 4GB RAM
* 2 CPU Cores
* 30GB minimum disk space and additional 20GB per installed XCode version

==== macOS Configuration Requirements
. Ansible requires SSH sudo access to the macOS server in order to correctly provision the server to support iOS builds. 
+
Enable SSH connection by following these steps:
+
* link:#create-macos-sudo-user[Create a sudo macOS user]
* link:#conf-remote-login-in-ansible-host[Configure Remote login(SSH) in Ansible]
* link:#add-macos-sudo-into-playbook[Add macOS sudo user credentials into Ansible Inventory file]

. link:#provide-macos-with-internet[Provide macOS server with Internet access to list of hosts]

[[create-macos-sudo-user]]
==== Create a sudo macOS User

Create a user with sudo permissions and SSH access on the macOS server. An example bash script is provided.

WARNING: Modify the script before you use it. Change the default `PASSWORD` and ensure that `USER_ID` is unassigned. An unmodified script will allow access to your machine with a default password.

.Default script behavior:

Create a user named `jenkins` with `USER_ID=550` and:

* Add the user to the `sudoers` file,
* Set `PASSWORD` to `Password1`,
* Add `jenkins` to the `admin` group.

IMPORTANT: Restart the server to implement the changes.

Use the following commands to download and execute the script:
[source,bash]
----
curl -O https://raw.githubusercontent.com/aerogear/aerogear-digger/master/admin/create-osx-user.sh
sudo bash create-osx-user.sh
----

[source,bash]
----
#!/usr/bin/env bash

USERNAME="jenkins"
PASSWORD="Password1"
REAL_NAME="Jenkins Agent"
GROUP_NAME="staff"

# the first user's id is 500, second is 501 ...
# picking a big number to be on the safe side.
# You can run this one to list UIDs
#   dscl . -list /Users UniqueID
USER_ID=550

# GID 20 is `staff`
GROUP_ID=20

############### end of parameters

. /etc/rc.common
dscl . create /Users/${USERNAME}
dscl . create /Users/${USERNAME} RealName ${REAL_NAME}
dscl . passwd /Users/${USERNAME} ${PASSWORD}

dscl . create /Users/${USERNAME} UniqueID ${USER_ID}
dscl . create /Users/${USERNAME} PrimaryGroupID ${GROUP_ID}
dscl . create /Users/${USERNAME} UserShell /bin/bash
dscl . create /Users/${USERNAME} NFSHomeDirectory /Users/${USERNAME}
dseditgroup -o edit -a ${USERNAME} -t user admin
cp -R /System/Library/User\ Template/English.lproj /Users/${USERNAME}
chown -R ${USERNAME}:${GROUP_NAME} /Users/${USERNAME}

echo "${USERNAME}  ALL=(ALL:ALL) ALL" >> /etc/sudoers

echo "Done creating OSX user - you may need to restart the osx server to apply all changes for the user ${USERNAME}"
----

[[conf-remote-login-in-ansible-host]]
==== Configure Remote Login(SSH) in Ansible Host
Enable the remotely running Ansible process to execute commands on the macOS server via SSH.

A sample script is provided below. Set `USERNAME` variable to match the name of the macOS user created in the previous step. This allows `USERNAME` to access the server through SSH with a password. 

WARNING: Understand what the script does before using it.

You can also add a public encryption key to the SSH `authorized_keys` file associated with the user. Private key of the asymmetric key pair is stored on the Ansible management node.

Use the following commands to download and execute the sample script:

[source,bash]
----
curl -O https://raw.githubusercontent.com/aerogear/aerogear-digger/master/admin/enable-osx-remote-login.sh
sudo bash enable-osx-remote-login.sh
----

[source,bash]
----
#!/usr/bin/env bash

# This script helps with enabling SSH for given OSX user.
# This script is not meant to be run in an automation. Run it manually.

USERNAME="jenkins"

# com.apple.access_ssh is a special group name on OSX.
# any user part of that group can have SSH connections in.
OSX_SSH_GROUP_NAME="com.apple.access_ssh"

systemsetup -setremotelogin on
# in order to check what groups are are there:
#   dscl . list /Groups PrimaryGroupID
# create a group for limiting SSH access
dseditgroup -o create -q ${OSX_SSH_GROUP_NAME}
# add user into this group
dseditgroup -o edit -a ${USERNAME} -t user ${OSX_SSH_GROUP_NAME}
# now, following should work  ---> ssh username@localhost
----

[[add-macos-sudo-into-inventory-file]]
==== Add macOS sudo Credentials into Ansible Inventory File

A number of tasks in the `provision-osx` Ansible role used in the installer require http://docs.ansible.com/ansible/latest/become.html[privilege escalation^], to allow Ansible to run commands as the `sudo` user.

* Set the `ansible_ssh_user` variable in Ansible inventory file to match the macOS user name created in previous steps.

* Set the user password. Use one of these methods:
** Put the user password into `ansible_sudo_pass` variable in Ansible inventory file.
** Use `--ask-sudo-pass` option with the user password as an argument for a command to run the Ansible installer playbook. See link:#run-digger-installer[Run Digger Installer].

[[provide-macos-with-access-to-hosts]]
==== Provide macOS with Internet Access to List of Hosts

IMPORTANT: Other external hosts may be required depending on what other packages you specify to install.

.Hosts and resources they provide:
|===
| Hostname | Provides

| https://github.com
| `Homebrew packages` and `Cocoapods`

| https://raw.githubusercontent.com
| `NVM - Node Version Manager`

| https://rvm.io
| `RVM - Ruby Version Manager`

| http://developer.apple.com
| `Apple Certificates` and `Xcode`

| https://npmjs.org
| `NPM packages`
|===