---
layout: post
section: docs
title: Digger Ansible macOS variables
---

== Install Homebrew

Installs Homebrew on the node.

This will also add any taps and packages specified in the options.

To run this section as a standalone step you must specify the
`osx_install_homebrew` tag.

|===
| Variable name | Description

|homebrew_version
|The version of Homebrew to install (git tag).
|homebrew_packages
|The packages to install using Homebrew. Format: { name: <PACKAGE_NAME> }.
|homebrew_repo
|The git repo where Homebrew resides (defaults to GitHub repo).
|homebrew_prefix -
|homebrew_install_path
|Where Homebrew will be installed, used as
`homebrew_prefix/homebrew_install_path`.
|homebrew_brew_bin_path
|Where brew will be installed.
|homebrew_taps
|A list of taps to add.
|===

== Install Ruby

Installs RVM along with a single version of Ruby. The version of Ruby to
install can be defined by a variable. The cocoapods gem will be installed,
other gems can be specified using the gem_packages variable.

To run this section as a standalone step you must specify the 
`osx_install_ruby` tag.

|===
| Variable name | Description

|rvm_install_url
|The URL of RVM installation script (defaults to GitHub release).

|rvm_install_file_name
|What to name the file on the node.

|rvm_gpg_url
|The URL of the RVM prerequisite gpg key.

|rvm_gpg_file_name
|What to name the file on the node.

|ruby_version
|The version of Ruby to install on the node.

|cocoapods_version
|The version of the Cocoapods gem to install.

|gem_packages
|A list of gems to install on the node.
Format: { name: <PACKAGE_NAME>, version: <PACKAGE_VERSION> }.
|===

== Install Nodejs

Installs NVM along with any versions of Nodejs specified through variables.
Packages from NPM can be defined also, however they will be installed globally.

To run this section as a standalone step you must specify the
`osx_install_nodejs` tag.

.Install Nodejs variables
|===
| Variable name | Description

|nvm_install_url
|The URL of NVM installation script (defaults to GitHub release).
|nvm_install_file_name
|What to name the file on the node.
|node_versions
|A list of Node versions to install.
|npm_packages
|A list of global NPM packages to install.
Format: { name: <PACKAGE_NAME>, version: <PACKAGE_VERSION> }.
|===

== Install Xcode

Installs Xcode CLI tools and Xcode versions specified. Installing Xcode a
single version of Xcode can take over 30 mi so please be patient during
these stages.

=== Two Factor Authentication (2FA) Support
If you have 2FA enabled for the Apple Developer Account you're specifying then
you will need to set the xcode_install_session_token option to a cookie
provided by authenticating with Apple. This can be done using Fastlane
Spaceship.

To run this section as a standalone step you must specify the
`osx_install_xcode` tag.

NOTE: Installed fastlane version must be >= 2.42.0

.Obtaining Apple Developer cookie for 2FA Xcode install
----
gem install fastlane -v '~> 2.42.0'
fastlane spaceauth -u <APPLE_DEVELOPER_USERNAME>
----

Follow the prompts. Once authenticated successfully a cookie will be logged to
the screen. Copy the cookie from `---\n` to the final `\n` and provide this as
the value for `xcode_install_session_token`.

Alternatively disable 2FA on the Apple Developer Account for the duration of
the Ansible job.

.Install Xcode variables
|===
| Variable name | Description

|xcode_install_user
|Apple Developer Account username. If this is not set then Xcode will not be
installed.
|xcode_install_password
|Apple Developer Account password. If this is not set then Xcode will not be
installed.
|xcode_install_session_token
|Apple Developer Account auth cookie from fastlane spaceauth command (For
accounts with 2FA enabled).
|xcode_versions
|A list of Xcode versions to install. These may take over 30 minutes each to
install.
|===

== Download Apple certificates

Downloads some required certificates into the node. Right now, the only
required certificate is Apple's WWDR certificate. This certificate will be
downloaded into the user's home directory.

To run this section as a standalone step you must specify the
`osx_download_certs` tag.

.Download Apple certificate variables
|===
| Variable name | Description

|apple_wwdr_cert_url
|Apple WWDR certificate URL. Defaults to Apple's official URL
|apple_wwdr_cert_file_name
|Output file name of the downloaded file. Defaults to AppleWWDRCA.cer.
|===

== Update Cocoapods

Executes pod repo update.

To run this section as a standalone step you must specify the
`osx_pod_repo_update` tag.

== Configure Buildfarm node

Creates a credential set in the build farm for the macOS nodes using the
provided keys. Add each machine as a node in the build farm, connecting through
SSH.

You will need to create a key pair using a tool such as ssh-keygen to allow the
Jenkins instance to connect with the macOS nodes.

To run this section as a standalone step you must specify the
`osx_configure_buildfarm` tag.

.Configure buildfarm node variables
|===
| Variable name | Description

|credential_private_key_path
|Location of the private key of the pair. This is stored in Jenkins and used to
SSH into the macOS node. If this is not set then this section will be skipped.
|credential_passphrase
|Passphrase of the private key. This is stored in Jenkins and used to SSH into
the macOS node. If this is not set then this section will be skipped.
|credential_public_key_path
|Location of the public key of the pair. If this is not set then this section
will be skipped.
|buildfarm_node_port
|The port to connect to the macOS node on. Defaults to 22.
|buildfarm_node_root_dir
|Root node of the node in Jenkins. Defaults to /Users/jenkins.
|buildfarm_credential_id
|Identifier for the Jenkins credential object. Defaults to
macOS_buildfarm_cred.
|buildfarm_credential_description
|Description of the Jenkins credential object.
|buildfarm_node_name
|Name of the slave/node in Jenkins. Defaults to macOS (<node_host_address>).
|buildfarm_node_labels
|List of labels to give the macOS node. Defaults to only ios.
|buildfarm_user_id
|Jenkins user. Defaults to admin.
|buildfarm_node_executors
|Number of executors (Jenkins configuration) on the macOS node. Defaults to 1.
|buildfarm_node_mode
|How the macOS node should be utilised. Should be one of:
|NORMAL
|Use this node as much as possible
|EXCLUSIVE
|Only build jobs with labels matching this node.
|buildfarm_node_description
|Description of the macOS node in Jenkins.
|Other options
|===

.Other variables
|===
| Variable name | Description

|remote_tmp_dir
|A directory where downloaded scripts and other miscellaneous files can be
stored for the duration of the job.
|project_name
|Name of the Jenkins project in OpenShift. Defaults to jenkins.
|===