== Running the Digger Installer

.To run the Digger installer, follow these steps:

. Clone the https://github.com/aerogear/digger-installer[Digger Installer GitHub repo^]

. Make a copy of the Ansible `inventory-sample` file from the repo, and update it with the information about your infrastructure
+
NOTE: For a full list of variables that can be configured via the inventory file refer to link:#installer-variables[Installer Variables].

. Run the playbook using the updated `inventory-sample` and follow the instructions printed in the terminal:

** Command to install Digger without a macOS server
+
----
ansible-playbook -i <your-inventory-sample> sample-build-playbook.yml --skip-tags=osx-provision
----

** Command to install Digger with a macOS server
+
----
ansible-playbook -i <your-inventory-sample> sample-build-playbook.yml
----

. Carry out manual steps during the installation
+
There are three points during the installation where there are manual steps required.
+
.. Accept the Android SDK Licence
.. Copy the server's (where Ansible task are running) public SSH key to Jenkins
.. Accept the Oracle Licence when installing Java on macOS server
+
Both of these steps are required for the installation to complete successfully. At each step the Ansible Installer will pause and prompt with the required actions.

.Ansible playbook will perform the following tasks:

* Verify and Install (if required) the minimum Java version
* Create a project in OpenShift
* Install Jenkins
* Install Android SDK to a Persistent Volume
* Configure Jenkins
* Setup macOS Server(s) (optional)
* Install Nagios
* Print URL and credentials for Jenkins and Nagios

NOTE: All tasks are idempotent. You can run them multiple times and they will produce the same results.