[[run-digger-installer]]
== Run Digger Installer

.To run the Digger installer, follow these steps:

. Clone the https://github.com/aerogear/digger-installer[Digger Installer GitHub repo^]

. Make a copy of the Ansible `inventory-sample` file from the repo, and update it with the information about your infrastructure
+
NOTE: For a full list of variables that can be configured via the inventory file see the link:#installer-variables[Installer Variables] section.

. Run the playbook using the updated `inventory-sample` and follow the instructions printed in the terminal.:

** Command to install digger without a macOS server
+
----
ansible-playbook -i <your-inventory-sample> sample-build-playbook.yml --skip-tags=osx-provision
----

** Command to install digger with a macOS server
+
----
ansible-playbook -i <your-inventory-sample> sample-build-playbook.yml
----

. Carry out manual steps during the installation
+
There are three points during the installation where there are manual steps required.
+
.. Accepting the Android SDK Licence
.. Copy the server's (where ansible task are running) public ssh key to Jenkins
.. Accept the Oracle Licence when installing Java on macOS server
+
Both of these steps are required for the installation to complete successfully. At each step the Ansible Installer will pause and prompt with the required actions.

During the installation the Ansible playbook will perform the following tasks:

* Verify and Install (if required) the minimum Java version
* Create a project in OpenShift
* Install Jenkins
* Install Android SDK to a Persistent Volume
* Configure Jenkins
* Setup macOS Server(s) (optional depending on command used)
* Install Nagios
* Print url and credentials for Jenkins and Nagios

--
NOTE: All tasks are idempotent. You can run them multiple times and they will produce the same results.
--
