---
layout: core
title: Aerogear Core
---
== AeroGear Core

AeroGear core take care of basics. For an abstraction of the connenctivity, use <<pipe, pipe>>, <<pipe, pipeline>> and
<<paging, paging>>. Anstracting your stoage level via <<store, DataManager>> and <<store, Store>>. You can even use our
convenient encrypted storage.


=== [[pipe]]Using pipe

AeroGear uses a Pipe metaphor for connecting to a remote web service. Pipe represents a server connection and are
responsible to communicate with the server in order to perform read/write operations. All methods on Pipe are
asynchronous and therefore use callback methods.

A Pipeline object represents a 'collection' of server connections (aka Pipes). It provides a standard way to communicate
 with the server no matter the data format or transport expected. It contains some simple management APIs to create and
 remove Pipe objects. Let's say you have a simple REST webservice with a base URL www.server.com/car,  here is how
 the pipe API is declined:

[width="60%",frame="topbot",options="header"]
|======================
|HTTP protocol |Pipe's method | Description
|GET:/car        |Pipe.read | return a JSON array
|POST:/car        |Pipe.save | create a car record
|PUT:/car/$id        |Pipe.save |update car
|DELETE:/car/$id        |Three items| delete car
|======================


[tabs]
[names="Java,iOS,JavaScript"]
  [source,java]
  ----
  public class Car {
      @RecordId
      public Long id;
      public String make;
      public String model;
      public String toString() {
        return String.format("{make:%s, model:%s}", make, model);
      }
  }
  Pipe<Car> pipe = new RestAdapter<Car>(Car.class, new URL("http://www.server.com/car"));
  ----
  [source,ios]
  ----
  AGPipeline* pipe = [AGPipeline pipelineWithBaseURL:[NSURL URLWithString:@"http://www.server.com/car"]];
  ----
  [source,javascript]
  ----
  TODO
  ----

If you are calling your link:/docs/specs/aerogear-android/org/jboss/aerogear/android/pipeline/Pipe.html[*Pipe*] from an
Activity or Fragment it is highly encouraged to create a static class which extends
link:/docs/specs/aerogear-android/org/jboss/aerogear/android/pipeline/AbstractActivityCallback.html[*AbstractActivityCallback*], link:/docs/specs/aerogear-android/org/jboss/aerogear/android/pipeline/support/AbstractFragmentActivityCallback.html[*AbstractFragmentActivityCallback*], link:/docs/specs/aerogear-android/org/jboss/aerogear/android/pipeline/AbstractFragmentCallback.html[*AbstractFragmentCallback*], or link:/docs/specs/aerogear-android/org/jboss/aerogear/android/pipeline/support/AbstractSupportFragmentCallback.html[*AbstractSupportFragmentCallback*].

=== Pagination