---
layout: basic
title: Setting up your development enivronment to use Apache Cordova
---

== Setting up your development enivronment to use Apache Cordova

This tutorial covers setting up Apache Cordova, as well as the iOS and Android development environments, required to build the hybrid application.


=== Apache Cordova

In order to build a Cordova iOS app, you need to install CordovaLib, Cordova Framework and Cordova XCode templates. PhoneGap helpfully provide builds of Cordova 2.0.0.

We recommend you use the latest release, which is 2.0.0 at the time of writing. Download https://github.com/phonegap/phonegap/zipball/2.0.0 and unzip. Take a note of where you unzipped Cordova to; we'll reference this location throughout the tutorials as `<CORDOVA_HOME>`.


=== iOS Build

In order to build a hybrid application for iOS, you'll need to install the iOS development environment:

* Mac OS X Lion (10.7) (or later)
* XCode 4.3 or later and the appropriate iOS SDK for your needs
* To test on iOS devices instead of the simulator:
** An Apple Developer account
** An iOS Development Certificate
** A provisioning profile for each device you plan to test with

You can read more about link:https://developer.apple.com/library/ios/#referencelibrary/GettingStarted/RoadMapiOS/chapters/Introduction.html[Start Developing iOS Apps Today].

=== Android Build

In order build a hybrid application for Android, you'll need to install the Android development environment:

* Java JDK 1.6
* At least the Android 2.3 SDK (installed via the Android SDK manager in the ADT)
