== Using Jenkinsfiles in an app

The below section outlines in further detail the steps taken via the Jenkinsfile to build an Application. Please refer to these sections if the provided Jenkinsfiles require altering or adjusting to work for building applications in your environment.

=== Checkout source code
To checkout a projects source code the `checkout` step can be used.

[source,groovy]
----
node("android"){
  ...
  stage("Checkout"){
    checkout scm
  }
  ...
}
----

=== Prepare the Environment/Application

==== Adding a configuration file (RHMAP only)
When building apps in RHMAP a properties file should be added to the app to
allow it to make backend requests. In Android this is a properties file named
`fhconfig.properties`, in iOS this is a plist file named `fhconfig.plist`. The
contents of these files is provided in the Jenkinsfile through
`params.FH_CONFIG_CONTENT`. Below are examples of populating the configuration
file for Android and iOS.

.fhconfig Android properties file
[source,groovy]
----
node(platform) {
  ...
  stage("Prepare"){
    writeFile file: 'app/src/main/assets/fhconfig.properties', text: params.FH_CONFIG_CONTENT
  }
  ...
}
----

.fhconfig iOS plist file
[source,groovy]
----
node(platform) {
  stage("Prepare") {
    writeFile: file: 'app/fhconfig.plist', text: params.FH_CONFIG_CONTENT
  }
}
----

==== Cordova preparation
For Cordova applications it is required to carry out steps to add and prepare the platform in the environment the application is building. Below are the steps required to complete this successfully. Note the multiple uses of the platform variable here. These steps are reused for building both "android" and "ios" depending on the platform value set.

[source,groovy]
----
node(platform) {
  stage("Prepare") {
    sh "cordova platform rm ${platform}"
    sh "cordova platform add ${platform}"
    sh "cordova prepare ${platform}"
  }
}
----

=== Building the Application

==== Building Applications with Xcode
To build Xcode projects you can use the `xcodeBuild` function in your
Jenkinsfile, this requires the `XC_VERSION` environment variable to be defined.
To sign the app the `xcodeBuild` function can then be used. See the link:#building-with-xcode[parameters section] for further details on values passed.

[source,groovy]
----
node('ios'){
  ...
  stage('Build') {
    withEnv(['XC_VERSION=8.3']) {
      xcodeBuild(
        cleanBeforeBuild: true,
        src: 'helloworld-ios-swift',
        schema: 'helloworld-ios-app',
        workspace: 'helloworld-ios-app',
        buildDir: 'build',
        sdk: 'iphoneos',
        version: '0.1-alpha',
        shortVersion: '0.1',
        bundleId: 'com.feedhenry.helloworld-ios-app',
        infoPlistPath: 'helloworld-ios-app/helloworld-ios-app-Info.plist',
        flags: '-fstack-protector -fstack-protector-all ENABLE_BITCODE=NO',
        autoSign: false
      )
    }
  }

  stage('CodeSign') {
    codeSign(
      profileId: "${params.BUILD_CREDENTIAL_ID}",
      clean: true,
      verify: true,
      ipaName: 'myapp',
      appPath: 'helloworld-ios-swift/build/Debug-iphoneos/helloworld-ios-app.app'
    )
  }
  ...
}
----

==== Building Cordova Applications

To build Cordova Applications the Jenkinsfile carries out seperate steps depending on whether the Application is being built for debug or release. Again note the use of the platform environment variable. Also BUILD_CONFIG is used in this case to decide the use of the `cordova build` command.

[source,groovy]
----
node(platform){
  ...
  stage('Build'){
      if (BUILD_CONFIG == 'debug') {
            sh "cordova build ${platform} --debug"
      } else {
            sh "cordova build ${platform} --release"
      }
  }

}
----

==== Building Android Applications

See the steps shown below showing the use `gradle` to build an Android Application for Debug or Release.

[source,groovy]
----
node("android"){
  ...
  stage("Build"){
    sh 'chmod +x ./gradlew'
    if (params.BUILD_CONFIG == 'release') {
      sh './gradlew clean assembleRelease' // builds app/build/outputs/apk/app-release.apk file
    } else {
      sh './gradlew clean assembleDebug' // builds app/build/outputs/apk/app-debug.apk
    }
  }
  ...
}
----


==== Using specific versions of Android SDK and Gradle

Android SDK and Gradle versions are defined in the Android project.

To change Android SDK version change the version information in app's `app/build.gradle` file:
[source,groovy]
----
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.3"

    defaultConfig {
        ...
        minSdkVersion 16
        targetSdkVersion 25
        ...
    }
...
}
----

See https://developer.android.com/studio/build/index.html[Android platform documents] for
explanation of these properties.

To change Gradle version, change the `distributionUrl` property in `gradle/wrapper/gradle-wrapper.properties`
in the app's source tree.
[source,properties]
----
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
----


=== Signing the Application

==== Signing Android build
When an Android apk is created it can be signed using the provided
`signAndroidApks` function. See the link:#sign-android-apks[parameters section] for additional information of values passed.

[source,groovy]
----
node("android"){
  ...
  stage("Sign"){
    if (params.BUILD_CONFIG == 'release') {
        signAndroidApks (
          keyStoreId: "${params.BUILD_CREDENTIAL_ID}",
          keyAlias: "${params.BUILD_CREDENTIAL_ALIAS}",
          apksToSign: "**/*-unsigned.apk",
          // uncomment the following line to output the signed APK to a
          separate directory as described above
          // signedApkMapping: [ $class: UnsignedApkBuilderDirMapping ],
        )
    } else {
      println('Debug Build - Using default developer signing key')
    }
  }
  ...
}
----



=== Function Parameters

[[sign-android-apks]]
==== signAndroidApks Parameters

The `signAndroidApks` function takes the following parameters.

.signAndroidApks options
|===
| Parameter | Description

| keyStoreId
| Keystore ID. This will be provided through the `BUILD_CREDENTIAL_ID`
parameter if the app is built through RHMAP.

| keyAlias
| Alias of the private key/certificate chain. This will be provided through the `BUILD_CREDENTIAL_ALIAS` parameter if the app is built through RHMAP.

| apksToSign
| A file name or glob pattern specifying the APK files to store.

| signedApkMapping
| Output the signed APK to a separate directory than the unsigned APK. Omit if
storing in the same directory.

| androidHome
| Override Android home directory.
|===




The function takes the following parameters.

[[building-with-xcode]]
==== Building with xCode Parameters
.xcodeBuild options
|===
| Parameter | Description

| cleanBeforeBuild
|	This will delete the build directories before invoking the build. This will
force the rebuilding of all dependencies and can make large projects take a lot
longer

| target
| The target to build. If left empty, this will build all targets in the
project. If you wish to build your binary and the unit test module, it is best
to do this as two separate steps each with their own target.

| sdk
| You only need to supply this value if you want to specify the SDK to build
against. If empty, the SDK will be determined by XCode.

| workspace
| Workspace to build from.

| buildDir
| The value to use for CONFIGURATION_BUILD_DIR setting (BUILD_DIR in >= 2.0.0).

| version
| Version of the app.

| shortVersion
| Short representation of the apps version.

| autoSign
| Whether to sign the app automatically or not.

| infoPlistPath
| Path to the apps plist file.

| flags
| Flags to add to the command that is executed.
|===

==== CodeSign Parameters

.codeSign options
|===
| Parameter | Description

| profileId
| ID of the developer profile. This will be provided through the
`BUILD_CREDENTIAL_ID` parameter if the app is built through RHMAP.

| clean
| Removes the previous signature (if any) before signing the artifact.

| verify
| Whether or not to verify the signature of the app after signing.

| ipaName
| Name of the created ipa file.

| appPath
| Path to the app to sign.
|===


=== Customising Jenkinsfile

A developer may wish to customise their `Jenkinsfile` to build an application. For instance they may want to install
a specific version of `nodejs` or build with a specific version of a dependency as an alternative to the default
version which is installed globally. An example snippet of each use case is outlined below:

==== Specifying a specific nodejs version

A developer needs to install dependencies on a `Node v6.9.5` runtime

----
node("android"){
  ...
  stage("Prepare"){
      sh '. $NVM_DIR/nvm.sh && nvm install 6.9.5 && nvm alias default 6.9.5'
      writeFile file: 'www/fhconfig.json', text: params.FH_CONFIG_CONTENT
      sh 'npm install --production'
      ...
  }
  ...
}
----


==== Installing and using a specific dependency version

A developer's Cordova application needs to be built with Cordova version 6.3.1

----
node("android"){
  ...

  stage("Prepare"){
      ...
      sh "npm install cordova@6.3.1"
      sh "node_modules/cordova/bin/cordova platform rm ${platform}"
      sh "node_modules/cordova/bin/cordova platform add ${platform}"
      sh "node_modules/cordova/bin/cordova prepare ${platform}"
      ...
  }
  ...
}
----
