---
layout: basic
title: Get Started on With AeroGear Android on NetBeans
---
== Get Started on With AeroGear Android on NetBeans


This guide will walk you through configuring your build environment to support AeroGear on Android as well as importing the project into NetBeans.  If you have already completed the link:../GetStartedAndroid/[command line getting started guide] then you can just open your project in NetBeans.  

After the library has been built, we will clone and run the https://github.com/aerogear/aerogear-android-todo[TODO sample application] to confirm it is working.

=== Requirements
* Java 6.0 (Java SDK 1.6)+
* link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[The latest Java version can be found on Oracle's site]
* Maven 3+
* link:http://maven.apache.org/download.html[The latest Maven version can be found on Apaches's site]
* Git
* link:http://git-scm.com/downloads[The latest Git version can be found at http://git-scm.com]
* Android SDK
* Need to have an AVD image running 4.1 (API level 16)
* link:http://developer.android.com/sdk/index.html[The latest Android SDK and instructions to install]


=== Setup Library
==== Setup Maven Android SDK Deployer

We need to have the https://github.com/mosabua/maven-android-sdk-deployer[Android Maven SDK Deployer] installed and configured.  These are only quickstart instructions, the Android Maven SDK Deployer GitHub has a much more in depth install guide.

You must have the version of the platform installed through the Android SDK as you are using for your profile.  In this example, make sure Android 4.1 is installed.

[source,bash]
----
git clone https://github.com/mosabua/maven-android-sdk-deployer.git
cd maven-android-sdk-deployer
export ANDROID_HOME=YOUR_ANDROID_SDK_DIRECTORY
mvn install -P 4.1
----

Now Maven will be able to include Android 4.1 as a dependency.  There are also profiles for other version of Android.

==== Downloading

* From the "Team" menu select "Git" and then "Clone"
* Enter "https://github.com/aerogear/aerogear-android.git" As your "Repository URL" and click "Next"
* Select the "master" branch and click "Next"
* Configure your "Parent Directory", "Clone Name" etc. and select "Finish" when done.
* Open the project

==== Building the Project

* Right click on the Project and select "Clean and Build"
* This will fire off the Maven Build.  You should see "BUILD SUCCESS" if everything went right.

=== Setup Sample TODO Project
==== Downloading

* Follow the same steps as you did to download the library, but use "https://github.com/aerogear/aerogear-android-todo.git" As your "Repository URL"

==== Running
* You should update your settings.xml file to include information about the AVD image you wish to use.  In this example we are loading an image named "JB".
.settings.xml
[source,xml]
-----
<settings>
    <activeProfiles>
        <activeProfile>local</activeProfile>
    </activeProfiles>
    <profiles>
        <profile>
            <id>local</id>
            <properties>
                <android.avd>JB</android.avd>
                <android.device>JB</android.device>
            </properties>
        </profile>
    </profiles>
</settings>
-----

* Edit the Run Action
** Right click on the project and select "Properties"
** In the window which appears select "Actions"
** Scroll through the "Actions" list until you see "Run project".  Select it
** Set "Execute Goals" to "android:deploy android:run"
** Add to "Set Properties" "undeployBeforeDeploy=true"
** You can now run the application.
==== Debugging
* Edit the Debug Action
** Right click on the project and select "Properties"
** In the window which appears select "Actions"
** Scroll through the "Actions" list until you see "Debug project".  Select it
** Set "Execute Goals" to "android:deploy android:run"
** Add to "Set Properties" the following:
[source]
----
undeployBeforeDeploy=true
runDebug=true
debug=true
----

** Start Android Monitor
    $ANDROID_HOME/tools/monitor
** Launch the application in debug mode from NetBeans
** Note the port shown in the monitor
** In NetBeans from "Debug" select "Attach Debugger" and enter into port the port number from the monitor.
** Your application should now be running in debug mode and breakpoints in NetBeans should work
