---
layout: basic
title: AeroGear JIRA Usage and Guidelines
---

== AeroGear JIRA Usage and Guidelines

This document describes the basic jira usage and guidelines for AeroGear. The most important point is _use your noodle_! Be descriptive, and link to forums, git, examples, and related jiras - it all helps get it resolved quickly.

.Creation
Anyone can create an issue. When the issue is created it should as a minimum have:

* a good summary/title (self-explanatory if possible)
* a component set in the jira
** If there is no matching component go to the https://lists.jboss.org/mailman/listinfo/aerogear-dev[AeroGear Development] mailing list and suggest one.
* an affects version if applicable
* a description with enough detail for us to reproduce the issue or understand what the feature is about.
** Attach tests, projects, logs, problem details, screenshots or even a http://www.jingproject.com/[screencast] to illustrate what you want to describe.

Assignment and fix versions should only be done by the committers.

.Assignment
Only committers/developers should assign the issue. Do not assign the issue to anyone unless it is yourself or you are sure they are supposed to work on the task.

The one who assign should also make sure to set:

* the fix version to indicate when it should be completed
* the Priority should be set in context of the fix version
** An issue can be trivial to implement but still be a Blocker if it is a must have feature or bug to have for the release.

.Discussions
Keep the description/comments updated as work progresses. This means comments related to reproducing, fixing or implementation requirements should be added. That saves time for anyone who is working with this issue to understand what actually should be done and how to verify it. Discussions in jira should be limited strictly to items related to the reproduction, description, and resolution of the issues. It should not evolve into a forum like discussion of questions. These are best moved to the forums.

.Fixing/Resolving
When an issue gets fixed the developer should make sure to:

* Follow instructions on Jira and GitHub pull requests here: link:../GitHubWorkflow[AeroGear GitHub Workflow &amp; Instructions]
* Resolve (not Close) the issue
* Comment on what was done.
** Sometimes "Done" is fine but a quick comment can save a lot of time.
