---
layout: basic
---

AeroGear Browser Support Targets
================================

Below is a listing of browsers that are targeted for all AeroGear related projects, and examples.  Given the broad and/or shifting nature of some of the technologies involved some examples may need different supported versions depending on features, frameworks, and goals for the specific example.  Any deviation from this should be documented in the example.

Desktop
-------

[options="header"]
|=================
|Browser|Versions|Notes
|Chrome|Current-1|	Auto-updates to latest version
|FireFox|Current-1|	Auto-updates to latest version
|Safari|5+|
|Internet Explorer|9+|
|Opera|TBD|	Auto-updates to latest version.  Not testing ATM
|=================

Mobile Devices
--------------

[options="header"]
|=================
|Browser|Versions|Notes
|Android Browser|2.3+, 3.2+, 4.x+|	
|iOS Safari|4.3, 5.x+|
|Windows Phone IE|TBD|Likely windows phone mango 7.5
|Mobile Chrome|TBD|
|Opera Mobile|TBD|
|=================

Notes
-----

HTML5 support varies by browser, however the browsers listed above should support all basic behaviors and functionality.  Some examples of acceptable differences are below.

* Browser support for field validation
** Chrome has the best support, other browsers have different levels of support
** No matter the browser support, the applications should still produce an invalid message, but it will be server based, not browser. 

* Input keyboard customization
** iOS browsers support custom keyboards for email, phone numbers, etc...
** Android browsers only support phone number custom keyboard
** No matter the support input should be possible