---
layout: basic
title: AeroGear UnifiedPush Android Variant REST APIs
---

APIs for working with Android Variants
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The RESTful APIs for working with +Android Variants+ are explained below:

Creation of an *Android Variant* (+HTTP POST+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

JSON Payload:
[source,json]
----
{
  "name" : "Android App",
  "description" : "The Android Variant",
  "googleKey" : "My Google API Key",
  "projectNumber" : "My Project Number / Sender ID"
}
----

URL:
[source,c]
----
https://SERVER:PORT/CONTEXT/rest/applications/{pushApplicationID}/android
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 201 Created+
The Body will contain (JSON) details about the created _Android Variant_:
[source,json]
----
{
  "id":"402880e43fa95bb3013faf3c41b40005",
  "name":"Android App",
  "description":"The Android Variant",
  "variantID":"04e9f747-d256-4a24-a0ac-29b9a15e37b1",
  "secret":"70135d26-696d-426a-8183-e1fd0fcb86fe",
  "developer":"admin",
  "installations":[],
  "googleKey":"My Google API Key",
  "projectNumber":"My Project Number / Sender ID"
}
----

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 400 Bad Request+
The format of the client request was incorrect (e.g. missing required values).

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource (_PushApplication_) does not exist.


Read all *Android Variants* for a *PushApplication* (+HTTP GET+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
https://SERVER:PORT/CONTEXT/rest/applications/{pushApplicationID}/android
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 200 OK+
The Body will contain a JSON list of the _Android Variants_, for the given PushApplication:

[source,json]
----
[
  {
    "id":"402880e43fa95bb3013faf3c41b40005",
    "name":"Android App",
    "description":"The Android Variant",
    ...
  },
  {...}
]
----


Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.


Read a specific *Android Variant* (+HTTP GET+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
https://SERVER:PORT/CONTEXT/rest/applications/{pushApplicationID}/android/{variantID}
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 200 OK+
The Body will contain (JSON) details about the specific _Android Variant_:
[source,json]
----
{
  "id":"402880e43fa95bb3013faf3c41b40005",
  "name":"Android App",
  "description":"The Android Variant",
  "variantID":"04e9f747-d256-4a24-a0ac-29b9a15e37b1",
  "secret":"70135d26-696d-426a-8183-e1fd0fcb86fe",
  "developer":"admin",
  "installations":[],
  "googleKey":"My Google API Key",
  "projectNumber":"My Project Number / Sender ID"
}
----


Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource (_Android Variant_) does not exist.


Update a specific *Android Variant* (+HTTP PUT+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

JSON Payload:
[source,json]
----
{
  "name" : "Android App",
  "description" : "A nice Android Variant",
  "googleKey" : "Updated Google API Key",
  "projectNumber" : "Updated Project Number / Sender ID"
}
----

URL:
[source,c]
----
https://SERVER:PORT/CONTEXT/rest/applications/{pushApplicationID}/android/{variantID}
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 204 No Content+
Empty body.

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 400 Bad Request+
The format of the client request was incorrect  (e.g. missing required values).

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource (_Android Variant_) does not exist.


Delete a specific *Android Variant* (+HTTP DELETE+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
https://SERVER:PORT/CONTEXT/rest/applications/{pushApplicationID}/android/{variantID}
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 204 No Content+
Empty body.

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource (_Android Variant_) does not exist.
