---
layout: basic
title: AeroGear UnifiedPush iOS Variant REST APIs
---

APIs for working with iOS Variants
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The RESTful APIs for working with +iOS Variants+ are explained below:

Creation of an *iOS Variant* (+HTTP POST+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For the +iOS+ variant, the MediaType is +multipart/form-data+.

Form Data:
[source,json]
----
{
  "name=iOS App",
  "description=The iOS Variant",
  "certificate=@/Users/matzew/Desktop/MyCert.p12"
  "passphrase=TopSecret"
}
----

URL:
[source,c]
----
http://server:port/context/rest/applications/{pushApplicationID}/iOS
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 201 Created+
The Body will contain (JSON) details about the created _iOS Variant_:
[source,json]
----
{
  "id":"402880e43fa95bb3013faf3c41b40005",
  "name":"iOS App",
  "description":"The iOS Variant",
  "variantID":"04e9f747-d256-4a24-a0ac-29b9a15e37b1",
  "secret":"70135d26-696d-426a-8183-e1fd0fcb86fe",
  ...
}
----

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 400 Bad Request+
The format of the client request was incorrect (e.g. missing required values).

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource (_PushApplication_) does not exist.


Read all *iOS Variants* for a *PushApplication* (+HTTP GET+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
http://server:port/context/rest/applications/{pushApplicationID}/iOS
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 200 OK+
The Body will contain a JSON list of the _iOS Variants_, for the given PushApplication:

[source,json]
----
[
  {
    "id":"402880e43fa95bb3013faf3c41b40005",
    "name":"iOS App",
    "description":"The iOS Variant",
    ...
  },
  {...}
]
----


Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.


Read a specific *iOS Variant* (+HTTP GET+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
http://server:port/context/rest/applications/{pushApplicationID}/iOS/{variantID}
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 200 OK+
The Body will contain (JSON) details about the specific _iOS Variant_:
[source,json]
----
{
  "id":"402880e43fa95bb3013faf3c41b40005",
  "name":"iOS App",
  "description":"The iOS Variant",
  "variantID":"04e9f747-d256-4a24-a0ac-29b9a15e37b1",
  "secret":"70135d26-696d-426a-8183-e1fd0fcb86fe",
  "developer":"admin",
  ...
}
----


Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource (_iOS Variant_) does not exist.


Update a specific *iOS Variant* (+HTTP PUT+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For the +iOS+ variant, the MediaType is +multipart/form-data+.

Form Data:
[source,json]
----
{
  "name=iOS App",
  "description=A nice iOS Variant",
  "certificate=@/Users/matzew/Desktop/SomeOtherCert.p12"
  "passphrase=ReallyTopSecret"
}
----

URL:
[source,c]
----
http://server:port/context/rest/applications/{pushApplicationID}/iOS/{variantID}
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 204 No Content+
Empty body.

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 400 Bad Request+
The format of the client request was incorrect  (e.g. missing required values).

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource (_iOS Variant_) does not exist.


Delete a specific *iOS Variant* (+HTTP DELETE+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
http://server:port/context/rest/applications/{pushApplicationID}/iOS/{variantID}
----

**NOTE:** This request additionally requires _Content-type: application/json_ header

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 204 No Content+
Empty body.

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource (_iOS Variant_) does not exist.
