---
layout: basic
title: AeroGear UnifiedPush SimplePush Variant REST APIs
---

APIs for working with SimplePush Variants
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The RESTful APIs for working with +SimplePush Variants+ are explained below:

Creation of an *SimplePush Variant* (+HTTP POST+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

JSON Payload:
[source,json]
----
{
  "name" : "SimplePush App",
  "description" : "The SimplePush Variant"
}
----

URL:
[source,c]
----
https://SERVER:PORT/CONTEXT/rest/applications/{pushApplicationID}/simplePush
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 201 Created+
The Body will contain (JSON) details about the created _SimplePush Variant_:
[source,json]
----
{
  "id":"402880e43fa95bb3013faf3c41b40005",
  "name":"SimplePush App",
  "description":"The SimplePush Variant",
  "variantID":"04e9f747-d256-4a24-a0ac-29b9a15e37b1",
  "secret":"70135d26-696d-426a-8183-e1fd0fcb86fe",
  "developer":"admin",
  "installations":[]
}
----

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 400 Bad Request+
The format of the client request was incorrect (e.g. missing required values).

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource (_PushApplication_) does not exist.


Read all *SimplePush Variants* for a *PushApplication* (+HTTP GET+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
https://SERVER:PORT/CONTEXT/rest/applications/{pushApplicationID}/simplePush
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 200 OK+
The Body will contain a JSON list of the _SimplePush Variants_, for the given PushApplication:

[source,json]
----
[
  {
    "id":"402880e43fa95bb3013faf3c41b40005",
    "name":"SimplePush App",
    "description":"The SimplePush Variant",
    ...
  },
  {...}
]
----


Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.


Read a specific *SimplePush Variant* (+HTTP GET+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
https://SERVER:PORT/CONTEXT/rest/applications/{pushApplicationID}/simplePush/{variantID}
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 200 OK+
The Body will contain (JSON) details about the specific _SimplePush Variant_:
[source,json]
----
{
  "id":"402880e43fa95bb3013faf3c41b40005",
  "name":"SimplePush App",
  "description":"The SimplePush Variant",
  "variantID":"04e9f747-d256-4a24-a0ac-29b9a15e37b1",
  "secret":"70135d26-696d-426a-8183-e1fd0fcb86fe",
  "developer":"admin",
  "installations":[]
}
----


Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource (_SimplePush Variant_) does not exist.


Update a specific *SimplePush Variant* (+HTTP PUT+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

JSON Payload:
[source,json]
----
{
  "name" : "SimplePush App",
  "description" : "A nice SimplePush Variant"
}
----

URL:
[source,c]
----
https://SERVER:PORT/CONTEXT/rest/applications/{pushApplicationID}/simplePush/{variantID}
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 204 No Content+
Empty body.

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 400 Bad Request+
The format of the client request was incorrect  (e.g. missing required values).

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource (_SimplePush Variant_) does not exist.


Delete a specific *SimplePush Variant* (+HTTP DELETE+)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,c]
----
https://SERVER:PORT/CONTEXT/rest/applications/{pushApplicationID}/simplePush/{variantID}
----

Success status code and returned body
+++++++++++++++++++++++++++++++++++++

* +HTTP/1.1 204 No Content+
Empty body.

Failure status code and description
++++++++++++++++++++++++++++++++++

* +HTTP/1.1 401 Unauthorized+
The request requires authentication.

* +HTTP/1.1 404 Not Found+
The requested resource (_SimplePush Variant_) does not exist.
