---
layout: basic
---

AeroGear Android Library 1.0.0 - DRAFT
======================================

This document covers the requirements, use-cases and planned API's for the AeroGear Android client library.  Completed functionality may be moved, removed, or updated in the aerogear-Android README.md file.

External References
-------------------

* link:https://github.com/aerogear/aerogear-android/[Github Repo]
* link:https://github.com/aerogear/aerogear-android/blob/master/README.md[README.md]
* link:https://issues.jboss.org/browse/AEROGEAR/component/12314945[AEROGEAR Jira component]

Deliverables
------------

* aerogear.jar
** Android SDK Installable Framework
* API & usage documentation
* Integration into an example application
** Possibly native version of TODO app
* Android SDK template application

Release Roadmap
---------------

Each library will have its own versioning.  Its Roadmap should be defined here.

1.0.0.Alpha1
~~~~~~~~~~~~

* Release along with AeroGear 1.0.0.M6
* link:https://github.com/aerogear/TODO/[TODO] integration for example app
* Solidify requirements
* Basic API structure
** CRUD
** Data-binding (via gson)
* Follow good Android practice re: background data transfers / services / etc
* First cut at user/auth integration (see link:AeroGearSecurity.asciidoc[AeroGear Security Plan]) (unsure if this will make it in or not - we should be able to design the API anyway, even if not-yet-functional)

1.0.0.Alpha2
~~~~~~~~~~~~

* Process API review comments from community
* More complete User/auth integration (begin to support OAuth?)
* Data synchronization design
* Query/search support?

1.0.0.Beta
~~~~~~~~~~

* [TBD]

1.0.0.Final
~~~~~~~~~~~

* Documentation review
* Community review + feedback
* 2nd example app?  (chat server?)

Android Specific Requirements
-----------------------------

* Push (link:http://developer.android.com/guide/google/gcm/index.html[Cloud Messaging]), including custom broadcast intents for data updates
* Server-backed ContentProvider?

For common cross-library requirements see:

* link:AeroGearPersistence.asciidoc[AeroGear Persistence Plan]
* link:AeroGearSecurity.asciidoc[AeroGear Security Plan]


*TODO* Complete
