---
layout: basic
title: AeroGear Android Authentication
---

== AeroGear Android Authentication

The goal of this guide is to provide a description of how authentication works in AeroGear Android and to give developers the ability to integrate their Android application with AeroGear-Controller based services as well as other RESTful services.

In RESTful services there are two basic parts of Authentication:

* Logging in and Fetching a token
* Applying the token to a request

This guide will go in depth on these two topics; however, we will also discuss briefly:

* Registering a new user
* Logging out of a service

== The Authentication API

Interaction with Authentication services is mediated using classes which implement the link:/docs/specs/aerogear-android/org/jboss/aerogear/android/authentication/AuthenticationModule.html[*AuthenticationModule*] interface, register themselves with the link:/docs/specs/aerogear-android/org/jboss/aerogear/android/authentication/impl/Authenticator.html[*Authenticator*] factory class, and apply themselves to a link:/docs/specs/aerogear-android/org/jboss/aerogear/android/pipeline/Pipe.html[*Pipe*] using link:/docs/specs/aerogear-android/org/jboss/aerogear/android/impl/pipeline/PipeConfig.html[*PipeConfig*].

link:/docs/specs/aerogear-android/org/jboss/aerogear/android/authentication/AuthenticationModule.html[*AuthenticationModule*] wraps up URL fields for enrolling, logging in, and logging out and defines the methods which call these URLs.  Once a login has been succesfully completed, it also provides an link:/docs/specs/aerogear-android/org/jboss/aerogear/android/authentication/AuthorizationFields.html[*AuthorizationFields*] object which encapuslates the necessary parameteres for applying authorization to a request via a link:/docs/specs/aerogear-android/org/jboss/aerogear/android/pipeline/Pipe.html[*Pipe*].

link:/docs/specs/aerogear-android/org/jboss/aerogear/android/authentication/impl/Authenticator.html[*Authenticator*] is a manager and a factory.  It can consume an link:/docs/specs/aerogear-android/org/jboss/aerogear/android/authentication/AuthenticationConfig.html[*AuthenticationConfig*] object and instanciate a module tuned to work with an AeroGear Controller based server, or you can create a custom link:/docs/specs/aerogear-android/org/jboss/aerogear/android/authentication/AuthenticationModule.html[*AuthenticationModule*] and register it with then link:/docs/specs/aerogear-android/org/jboss/aerogear/android/authentication/impl/Authenticator.html[*Authenticator*].  link:/docs/specs/aerogear-android/org/jboss/aerogear/android/authentication/impl/Authenticator.html[*Authenticator*] also supplies getters which can wrap any link:/docs/specs/aerogear-android/org/jboss/aerogear/android/authentication/AuthenticationModule.html[*AuthenticationModule*] in a proxy which delegates calls to the server to an Android Loader.

*AbstractAuthenticationModule* is a convenience class for integrating with non AeroGear REST services.  It is also useful for when you want to only support a subset of the link:/docs/specs/aerogear-android/org/jboss/aerogear/android/authentication/AuthenticationModule.html[*AuthenticationModule*]'s functionality, and it configures a THREAD_POOL_EXECUTOR for you to delegate your network calls to.  

=== Using Authentication: The TODO App
For an example of using the Authentication API to connect to a AeroGear Controller, let\'s look at https://github.com/aerogear/aerogear-android-todo.

==== Setting up Authentication

.ToDoApplication
[source,java]
----

//Class definitions, exceptions, and full configuration of Pipes are snipped for clarity.

URL baseURL = new URL("http://todo-aerogear.rhcloud.com/todo-server");
private Pipeline pipeline = new Pipeline(baseURL);;
private Authenticator auth = new Authenticator(baseURL);

@Override
public void onCreate() {
	super.onCreate();
	
	//Supply configuration
	AuthenticationConfig config = new AuthenticationConfig();
	config.setEnrollEndpoint("/auth/register");

	//Create AuthenticationModule
	AuthenticationModule authModule = auth.auth("login", config);

	//Add AuthenticationModule to Pipe
	PipeConfig pipeConfigTask = new PipeConfig(baseURL, Task.class);
	pipeConfigTask.setAuthModule(authModule);
	pipeline.pipe(Task.class, pipeConfigTask);

}
----

==== Using Authentication

While the application is not logged in, link:/docs/specs/aerogear-android/org/jboss/aerogear/android/authentication/AuthenticationModule.html[*AuthenticationModule*] will stay out of the way.  However, interacting with authentication is this simple.

.AuthenticationMethodsExample
[source,java]
----
public void login(FragmentActivity activity, String username, String password,
			Callback<HeaderAndBody> callback) {
	authenticator.get("login", activity).login(username, password, callback);

}

public void logout(FragmentActivity activity, Callback<Void> callback) {
	authenticator.get("login", activity).logout(callback);
}

public void enroll(FragmentActivity activity, String firstName, String lastName, String emailAddress,
		String username, String password, String role,
		Callback<HeaderAndBody> callback) {

	HashMap<String, String> userData = new HashMap<String, String>();
	userData.put("firstname", firstName);
	userData.put("lastname", lastName);
	userData.put("email", emailAddress);
	userData.put("username", username);
	userData.put("password", password);
	userData.put("role", role);

	authenticator.get("login", activity).enroll(userData, callback);
}
----

=== Using Authentication: Custom Applications

AeroGear Android\'s Authentication API provides a framework for supporting many other RESTful services.  Obviously this guide cannot cover all of them, but we will review custom authentication with one third party service, link:http://www.reddit.com[Reddit].  

To retrieve the tokens Reddit requires for accessing a user\'s data we must log in as that user.  Reddit\'s login service consumes a HTTP POST at the URL http://www.reddit.com/api/login/%username with the Content-Type of application/x-www-form-urlencoded.  The request body is required to also the parameters `user`, `passwd`, and `api_type`.  It returns a JSON response with parameters "json.data.modhash" and "json.data.cookie".  These parameters are extracted as part of the `login` method and passed to the link:/docs/specs/aerogear-android/org/jboss/aerogear/android/pipeline/Pipe.html[*Pipe*] implementation from the `getAuthorizationFields` method.

==== RedditAuthenticationModule

.RedditAuthenticationModule
[source,java]
----
public class RedditAuthenticationModule extends AbstractAuthenticationModule {
 
    private String authToken = "";
    private String modHash = ""; 

    public void login(final String username, final String password,
		    final Callback<HeaderAndBody> callback) {
        THREAD_POOL_EXECUTOR.execute(new Runnable() {
		private Exception exception;
		private HeaderAndBody result;

		@Override
		public void run() {
		        try {
		        	HttpProvider provider = 
					new HttpRestProvider( new URL(String.format("http://www.reddit.com/api/login/%s", username)) );
		        	provider.setDefaultHeader("User-Agent", "AeroGear StoryList Demo /u/secondsun");
		        	provider.setDefaultHeader("Content-Type", "application/x-www-form-urlencoded");
		        	
				result = provider.post(String.format("user=%s&api_type=json&passwd=%s",username,password);

				String json = new String(result.getBody());
				JsonObject authenticationObject = new JsonParser().parse(json).getAsJsonObject()
										  .get("json").getAsJsonObject()
										  .get("data").getAsJsonObject();
				
				modHash = authenticationObject.get("modhash").getAsString();
				authToken = authenticationObject.get("cookie").getAsString();
				
				isLoggedIn = true;
		        } catch (Exception e) {
		            exception = e;
		        }

			if (exception == null) {
		            callback.onSuccess(this.result);
		        } else {
		            callback.onFailure(exception);
		        }
		        
		}


	});


	}
 
    public AuthorizationFields getAuthorizationFields() {
 
        AuthorizationFields fields = new AuthorizationFields();
        fields.addHeader("User-Agent", "AeroGear StoryList Demo /u/secondsun");
        if (isLoggedIn) {
            fields.addHeader("Cookie", "reddit_session="+authToken);
            fields.addQueryParameter("uh", modHash);
        }
        return fields;
    }
     
}
----



