---
layout: post
section: guides
title: How to build AeroGear Android
---


== Prereqs

* link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java 7]
* link:http://maven.apache.org/[Maven 3.1.1]
* Latest link:https://developer.android.com/sdk/index.html[Android SDK] and link:http://developer.android.com/tools/revisions/platforms.html[Platform version]
* Latest link:http://developer.android.com/tools/support-library/index.html[Android Support Library] and link:http://developer.android.com/google/play-services/index.html[Google Play Services]
* Latest link:https://github.com/mosabua/maven-android-sdk-deployer[Maven Android SDK Deployer]

== Note
If you only want to build Android applications using AeroGear you do not need to build the project from source.  Our compiled ready to go binaries are available in Maven Central.  If you want to contribute to AeroGear Android then read on.
== Building

AeroGear's Android libraries are built as apklib projects using Maven, but Google does not ship all the required libraries to Maven Central. You must locally deploy them using the link:https://github.com/mosabua/maven-android-sdk-deployer[maven-android-sdk-deployer].

=== Checkout maven-android-sdk-deployer
```
git clone git://github.com/mosabua/maven-android-sdk-deployer.git
```

=== Install Android platform
```
cd $PWD/maven-android-sdk-deployer/platforms/android-21
mvn install -N --quiet
```

=== Install locally google-play-services
```
cd $PWD/maven-android-sdk-deployer/extras/google-play-services
mvn  install -N --quiet
```

=== Install locally compatibility-v4
```
cd $PWD/maven-android-sdk-deployer/extras/compatibility-v4
mvn install -N --quiet
```

=== Install locally compatibility-v7-appcompat
```
cd $PWD/maven-android-sdk-deployer/extras/compatibility-v7-appcompat
mvn install -N --quiet
```

=== Install locally google-m2repository
```
cd $PWD/maven-android-sdk-deployer/repositories/google-m2repository
mvn install -N --quiet
```

